algoritmo "semnome"
// Função :O programa serve para dividir o valor total de uma compra em 5 parcelas iguais, sem juros, e mostrar quanto será o valor de cada prestação.
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
prestacao , valor : real
inicio
// Seção de Comandos 

escreval("Digite o valor da compra R$ : ")
leia(valor)


prestacao <- valor / 5

escreval("O valor de cada prestação é: R$ ", prestacao:0:2)



fimalgoritmo

