algoritmo "semnome"
// Função :Mostrar se o numero digitado estado no intervalo entre 100 e 200.
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
numeroNoIntervalo, n1 : inteiro
inicio
// Seção de Comandos 
escreval("Escreva um número : ")
leia(n1)

se (n1 >= 100) e (n1  <= 200 ) entao

escreva("O número está no intervalo entre 100 e 200 ")
senao
escreva("O número não está no intervalo entre 100 e 200 ")

fimse



fimalgoritmo

