algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2025
// Seção de Declarações 
var
x, num, intervalo: inteiro
inicio
// Seção de Comandos 

para x de 1 ate 80 faca
escreva("digite um numero: ")
leia(num)

se num >= 10 entao
se num <= 150 entao
intervalo <- intervalo + 1

fimse

escreval("Ao total, foram digitados",intervalo," numeros no intervalo entre 10 e 150")


fimalgoritmo

