algoritmo "semnome"
// Função :A funçao desse algoritimo e receber um numero e dizer se esse numero e maior que 80 menor que 25 ou igual a 40.
// Autor :
// Data : 13/10/2025
// Seção de Declarações 
var
num: inteiro
inicio
escreval("digite um numero: ")
leia(num)

se(num>80) ou (num<25) ou (num=40) entao
escreval("o numero atende a condiçao.")
senao
escreval("o numero nao atende a condiçao.")
fimse
fimalgoritmo

