algoritmo "semnome"
// Função :Um algoritimo que pega um numero de 1 a 12 e mostre o mes correspondente.
// Autor :
// Data : 14/10/2025
// Seção de Declarações 
var
mes: inteiro
inicio
escreva("digite o numero do mes (1 a 12): ")
leia(mes)

escolha mes
caso 1
escreval("janeiro")
caso 2
escreval("fevereiro")
caso 3
escreval("março")
caso 4
escreval("abril")
caso 5
escreval("maio")
outrocaso
escreval("mes invalido")
fimescolha
fimalgoritmo

