algoritmo "exercicio 4"
// Função :
// Autor : rhuan
// Data : 23/09/2025
// Seção de Declarações 
var
 nome: caracter
 salario: real
 vendas: real

inicio
 escreval("nome do funcionario")
 leia(nome)
 escreval("salario")
 leia(salario)
 escreval("vendas")
 leia(vendas)
 escreval("a cmissao e de :", vendas *0.15)
 escreval("O total no fim do mes e de:",salario + vendas * 0.15)

  
fimalgoritmo
